# Site settings
title: Charles Qi's Blog
email: 
description: "Writings on AI, investment and life hacks."
baseurl: ""
url: "https://charlesrqi.com"
baseurl: "/blog"
twitter_username: charles_rqi 
github_username:

# Build settings
markdown: kramdown
permalink: pretty

highlighter: rouge
kramdown:
  input: GFM
  auto_ids: true
  syntax_highlighter: rouge
